// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDePTKBYCOpZHN7mmGZDaIlDvTF_r2X2Qk',
    appId: '1:9903814958:web:a3a232160c824c56ee62bf',
    messagingSenderId: '9903814958',
    projectId: 'installer-project-assist',
    authDomain: 'installer-project-assist.firebaseapp.com',
    storageBucket: 'installer-project-assist.firebasestorage.app',
    measurementId: 'G-8P8M3H8HTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXdr2dL90A_EGtL-1R5TDtpc6RdEh_ESo',
    appId: '1:9903814958:android:77cfcc5415f43b72ee62bf',
    messagingSenderId: '9903814958',
    projectId: 'installer-project-assist',
    storageBucket: 'installer-project-assist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK8FEOVF9wL8q2N7QkF_BHgWG4W4YrR7s',
    appId: '1:9903814958:ios:511655e9917f8b52ee62bf',
    messagingSenderId: '9903814958',
    projectId: 'installer-project-assist',
    storageBucket: 'installer-project-assist.firebasestorage.app',
    iosBundleId: 'com.invoiceApp.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK8FEOVF9wL8q2N7QkF_BHgWG4W4YrR7s',
    appId: '1:9903814958:ios:511655e9917f8b52ee62bf',
    messagingSenderId: '9903814958',
    projectId: 'installer-project-assist',
    storageBucket: 'installer-project-assist.firebasestorage.app',
    iosBundleId: 'com.invoiceApp.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDePTKBYCOpZHN7mmGZDaIlDvTF_r2X2Qk',
    appId: '1:9903814958:web:202f5af66c9c53bfee62bf',
    messagingSenderId: '9903814958',
    projectId: 'installer-project-assist',
    authDomain: 'installer-project-assist.firebaseapp.com',
    storageBucket: 'installer-project-assist.firebasestorage.app',
    measurementId: 'G-B55YTP1KHR',
  );

}